### ISSUE TITLE
Avatar is not necessarily owner

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/zodiac-module-gnomad#1]
We should replace "avatar" in the notice with "owner", since the avatar is not necessarily the owner, and these functions use the `onlyOwner` modifier.

https://github.com/gnosis/zodiac-module-gnomad/blob/fc91e8baa0925be7eb481ac9004fbd87db7feaa1/contracts/GnomadModule.sol#L81-L82

https://github.com/gnosis/zodiac-module-gnomad/blob/fc91e8baa0925be7eb481ac9004fbd87db7feaa1/contracts/GnomadModule.sol#L89-L90

https://github.com/gnosis/zodiac-module-gnomad/blob/fc91e8baa0925be7eb481ac9004fbd87db7feaa1/contracts/GnomadModule.sol#L97-L98

**Comment by nginnever** [comment]
ahh yes, renamed
